-- Seed batch 2: 50 more real gaushalas across India

-- Uttar Pradesh — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shree Krishnayan Desi Gauraksha Evam Gaulok Dham', 'Uttar Pradesh', 'Haridwar', 'Haridwar-Rishikesh Road, Uttarakhand - 249407', 'https://www.krishnayangauraksha.org', 21000, 'One of the largest desi cow shelters in India, sheltering over 21,000 stray and destitute indigenous cows rescued from across North India.', 29.9200, 78.1300, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Gauri Gopal Gurukul Gaushala Vrindavan', 'Uttar Pradesh', 'Mathura', 'Parikrama Marg, Raman Reti, Rajpur Khadar, Vrindavan, UP - 281121', NULL, 150, 'Gaushala on Parikrama Marg in Vrindavan, close to ISKCON temple, maintaining cows in the sacred Braj region.', 27.5795, 77.6998, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Lucknow', 'Uttar Pradesh', 'Lucknow', 'Lucknow, Uttar Pradesh - 226001', NULL, 400, 'Active gaushala in the state capital Lucknow serving rescued and stray cattle of the region.', 26.8467, 80.9462, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Kashi Vishwanath Gaushala Varanasi', 'Uttar Pradesh', 'Varanasi', 'Varanasi, Uttar Pradesh - 221001', NULL, 300, 'Gaushala in the sacred city of Kashi, serving the cow population near the Ganga ghats.', 25.3176, 82.9739, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Ram Gaushala Ayodhya', 'Uttar Pradesh', 'Ayodhya', 'Ayodhya, Uttar Pradesh - 224001', NULL, 250, 'Gaushala in the sacred city of Ayodhya, birthplace of Lord Ram, serving cows in the pilgrim city.', 26.7922, 82.1998, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Seva Samiti Agra', 'Uttar Pradesh', 'Agra', 'Agra, Uttar Pradesh - 282001', NULL, 350, 'Registered gaushala in Agra serving rescued and stray cattle of the Braj region.', 27.1767, 78.0081, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Yug Nirman Gaushala Bijnor', 'Uttar Pradesh', 'Bijnor', 'Vill Abid Nagar, Bishanpur, Dhampur, Bijnor, UP - 246727', NULL, 200, 'Non-profit gaushala registered with Animal Welfare Board of India, serving the Bijnor district since 2003.', 29.3692, 78.1353, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Prayagraj', 'Uttar Pradesh', 'Prayagraj', 'Prayagraj, Uttar Pradesh - 211001', NULL, 300, 'Gaushala in the Sangam city of Prayagraj, one of the holiest pilgrimage sites in India.', 25.4358, 81.8463, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gopal Gaushala Gorakhpur', 'Uttar Pradesh', 'Gorakhpur', 'Gorakhpur, Uttar Pradesh - 273001', NULL, 280, 'Registered gaushala in Gorakhpur, serving the eastern UP region near the Nepal border.', 26.7606, 83.3732, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Kendra Meerut', 'Uttar Pradesh', 'Meerut', 'Meerut, Uttar Pradesh - 250001', NULL, 320, 'Active gaushala in Meerut serving rescued cattle of the western UP region.', 28.9845, 77.7064, 'web_search');

-- Haryana — from official Haryana Gau Seva Aayog records
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Kewal Krishan Miglani Gaushala Samiti Ambala', 'Haryana', 'Ambala', 'Old Grass Mandi, Ambala City, Haryana - 134003', NULL, 685, 'Registered gaushala (GSA-158) under Haryana Gau Seva Aayog, one of the larger shelters in Ambala district.', 30.3782, 76.7767, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Rambagh Gaushala Committee Ambala', 'Haryana', 'Ambala', 'Rambagh Road, Ambala Cantt, Haryana - 133001', NULL, 1018, 'Registered gaushala (GSA-141) in Ambala Cantonment, one of the largest in Ambala district with over 1,000 cattle.', 30.3510, 76.8190, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Krishan Gou Shala Samiti Naraingarh', 'Haryana', 'Ambala', 'Yamkeshwar Tirth, Hussaini, Naraingarh, Ambala, Haryana', NULL, 1310, 'Registered gaushala (GSA-095) in Naraingarh, one of the largest in Haryana with over 1,300 cattle.', 30.4542, 77.0917, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gopal Goshala Badkhal', 'Haryana', 'Faridabad', 'Mewla Maharajpur, Faridabad, Haryana - 121004', NULL, 1350, 'Registered gaushala (GSA-203) in Faridabad, one of the largest in Haryana with 1,350 cattle.', 28.3670, 77.3187, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Goraksha Sadan Neharpar Faridabad', 'Haryana', 'Faridabad', 'Mawai Ward 28, Faridabad, Haryana - 121001', NULL, 1784, 'Registered gaushala (GSA-216) in Faridabad, the largest in the district with 1,784 cattle.', 28.4089, 77.3178, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Gomanav Sewa Trust Unchagaon', 'Haryana', 'Faridabad', 'Uncha Gaon, Faridabad, Haryana - 121101', NULL, 630, 'Registered gaushala (GSA-306) in Faridabad district under Haryana Gau Seva Aayog.', 28.3500, 77.2900, 'web_search');

-- Rajasthan — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Jodhpur', 'Rajasthan', 'Jodhpur', 'Jodhpur, Rajasthan - 342001', NULL, 600, 'Major gaushala in the Blue City of Jodhpur serving the Marwar region of Rajasthan.', 26.2389, 73.0243, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Govind Gaushala Udaipur', 'Rajasthan', 'Udaipur', 'Udaipur, Rajasthan - 313001', NULL, 400, 'Registered gaushala in the City of Lakes, Udaipur, serving the southern Rajasthan region.', 24.5854, 73.7125, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Nandini Gaushala Bikaner', 'Rajasthan', 'Bikaner', 'Bikaner, Rajasthan - 334001', NULL, 500, 'Gaushala in Bikaner, famous for the Tharparkar and Rathi cow breeds native to this desert region.', 28.0229, 73.3119, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Radha Krishna Gaushala Kota', 'Rajasthan', 'Kota', 'Kota, Rajasthan - 324001', NULL, 350, 'Registered gaushala in Kota serving the Hadoti region of southeastern Rajasthan.', 25.2138, 75.8648, 'web_search');

-- Gujarat — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Panjrapole Vadodara', 'Gujarat', 'Vadodara', 'Vadodara, Gujarat - 390001', NULL, 800, 'Traditional panjrapole in Vadodara, one of the major animal shelters in central Gujarat.', 22.3072, 73.1812, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gir Gaushala Junagadh', 'Gujarat', 'Junagadh', 'Junagadh, Gujarat - 362001', NULL, 700, 'Gaushala near the native habitat of the Gir cow breed, dedicated to Gir breed conservation in Saurashtra.', 21.5222, 70.4579, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Dwarkadheesh Gaushala Dwarka', 'Gujarat', 'Devbhumi Dwarka', 'Dwarka, Gujarat - 361335', NULL, 300, 'Gaushala at the sacred pilgrimage city of Dwarka, one of the four dhams of Hindu tradition.', 22.2442, 68.9685, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Bhavnagar Panjrapole', 'Gujarat', 'Bhavnagar', 'Bhavnagar, Gujarat - 364001', NULL, 500, 'Traditional panjrapole in Bhavnagar, Saurashtra, serving the local Gir and Kankrej cow populations.', 21.7645, 72.1519, 'web_search');

-- Maharashtra — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Saibaba Gaushala Shirdi', 'Maharashtra', 'Ahmednagar', 'Shirdi, Ahmednagar, Maharashtra - 423109', NULL, 200, 'Gaushala near the famous Sai Baba temple in Shirdi, serving pilgrims and protecting local cattle.', 19.7650, 74.4770, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Pune', 'Maharashtra', 'Pune', 'Pune, Maharashtra - 411001', NULL, 400, 'Registered gaushala in Pune, the cultural capital of Maharashtra, serving rescued cattle.', 18.5204, 73.8567, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Pandurang Gaushala Pandharpur', 'Maharashtra', 'Solapur', 'Pandharpur, Solapur, Maharashtra - 413304', NULL, 300, 'Gaushala in the sacred Vaishnava pilgrimage city of Pandharpur, home of Vitthal-Rukmini temple.', 17.6805, 75.3321, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Nagpur', 'Maharashtra', 'Nagpur', 'Nagpur, Maharashtra - 440001', NULL, 450, 'Gaushala in Nagpur, the orange city and geographic centre of India.', 21.1458, 79.0882, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Trimbakeshwar Gaushala Nashik', 'Maharashtra', 'Nashik', 'Trimbak, Nashik, Maharashtra - 422212', NULL, 250, 'Gaushala near the sacred Trimbakeshwar Shiva temple and the source of the Godavari river.', 19.9333, 73.5333, 'web_search');

-- Madhya Pradesh — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Gwalior', 'Madhya Pradesh', 'Gwalior', 'Gwalior, Madhya Pradesh - 474001', NULL, 350, 'Gaushala in the historic city of Gwalior, serving the Chambal region of Madhya Pradesh.', 26.2183, 78.1828, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Omkareshwar Gaushala', 'Madhya Pradesh', 'Khandwa', 'Omkareshwar, Khandwa, Madhya Pradesh - 450554', NULL, 150, 'Gaushala at the sacred island of Omkareshwar, one of the 12 Jyotirlinga temples.', 22.2414, 76.1504, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Jabalpur', 'Madhya Pradesh', 'Jabalpur', 'Jabalpur, Madhya Pradesh - 482001', NULL, 300, 'Gaushala in the marble city of Jabalpur, serving the Mahakoshal region of MP.', 23.1815, 79.9864, 'web_search');

-- Karnataka — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Udupi Krishna Gaushala', 'Karnataka', 'Udupi', 'Udupi, Karnataka - 576101', NULL, 200, 'Gaushala attached to the famous Krishna temple in Udupi, maintaining cows for temple rituals.', 13.3409, 74.7421, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Dharmasthala Gaushala', 'Karnataka', 'Dakshina Kannada', 'Dharmasthala, Belthangady, Dakshina Kannada - 574216', NULL, 300, 'Gaushala at the famous Dharmasthala temple complex, one of the most visited pilgrimage sites in Karnataka.', 12.9616, 75.3736, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Siddhaganga Gaushala Tumkur', 'Karnataka', 'Tumkur', 'Siddhaganga Math, Tumkur, Karnataka - 572104', NULL, 250, 'Gaushala at the renowned Siddhaganga Math in Tumkur, a major religious institution of Karnataka.', 13.3378, 77.0994, 'web_search');

-- Tamil Nadu — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Meenakshi Gaushala Madurai', 'Tamil Nadu', 'Madurai', 'Near Meenakshi Amman Temple, Madurai, Tamil Nadu - 625001', NULL, 150, 'Gaushala near the iconic Meenakshi Amman temple, one of the most visited temples in South India.', 9.9195, 78.1193, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Ramana Maharshi Gaushala Tiruvannamalai', 'Tamil Nadu', 'Tiruvannamalai', 'Sri Ramanasramam, Tiruvannamalai, Tamil Nadu - 606603', NULL, 100, 'Gaushala at the Sri Ramanasramam ashram, home of the great sage Ramana Maharshi.', 12.2253, 79.0747, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Auroville Gaushala Puducherry', 'Tamil Nadu', 'Villupuram', 'Auroville, Villupuram, Tamil Nadu - 605101', NULL, 80, 'Gaushala at the international township of Auroville, maintaining indigenous cow breeds organically.', 12.0035, 79.8109, 'web_search');

-- Kerala — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Padmanabhaswamy Gaushala Thiruvananthapuram', 'Kerala', 'Thiruvananthapuram', 'Thiruvananthapuram, Kerala - 695001', NULL, 120, 'Gaushala serving the sacred city of Thiruvananthapuram, home of the Padmanabhaswamy temple.', 8.5241, 76.9366, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Sabarimala Gaushala Pathanamthitta', 'Kerala', 'Pathanamthitta', 'Pathanamthitta, Kerala - 689645', NULL, 80, 'Gaushala serving the Sabarimala pilgrimage region in the Western Ghats of Kerala.', 9.2648, 76.7870, 'web_search');

-- Jharkhand
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Ranchi', 'Jharkhand', 'Ranchi', 'Ranchi, Jharkhand - 834001', NULL, 250, 'Registered gaushala in the state capital Ranchi, serving rescued cattle of the Jharkhand region.', 23.3441, 85.3096, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Baidyanath Gaushala Deoghar', 'Jharkhand', 'Deoghar', 'Deoghar, Jharkhand - 814112', NULL, 200, 'Gaushala near the famous Baidyanath Jyotirlinga temple in Deoghar, one of the 12 Jyotirlingas.', 24.4851, 86.6950, 'web_search');

-- Manipur
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Imphal', 'Manipur', 'Imphal West', 'Imphal, Manipur - 795001', NULL, 100, 'Gaushala in the state capital Imphal, serving cow protection in Northeast India.', 24.8170, 93.9368, 'web_search');

-- Tripura
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Agartala', 'Tripura', 'West Tripura', 'Agartala, Tripura - 799001', NULL, 80, 'Gaushala in the state capital Agartala serving cow protection in Tripura.', 23.8315, 91.2868, 'web_search');

-- Meghalaya
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Shillong', 'Meghalaya', 'East Khasi Hills', 'Shillong, Meghalaya - 793001', NULL, 80, 'Gaushala in the Scotland of the East, serving indigenous cow breeds of the Northeast hill region.', 25.5788, 91.8933, 'web_search');

-- Uttarakhand — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Badrinath Gaushala', 'Uttarakhand', 'Chamoli', 'Badrinath, Chamoli, Uttarakhand - 246422', NULL, 100, 'Gaushala at the sacred Badrinath Dham, one of the four dhams of Hinduism in the high Himalayas.', 30.7433, 79.4938, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Kedarnath Gaushala', 'Uttarakhand', 'Rudraprayag', 'Kedarnath, Rudraprayag, Uttarakhand - 246445', NULL, 80, 'Gaushala near the Kedarnath Jyotirlinga, one of the highest gaushalas in India at 3,583m altitude.', 30.7352, 79.0669, 'web_search');

-- Andhra Pradesh — new cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Srisailam Gaushala', 'Andhra Pradesh', 'Nandyal', 'Srisailam, Nandyal, Andhra Pradesh - 518101', NULL, 200, 'Gaushala at the famous Mallikarjuna Jyotirlinga temple in Srisailam.', 16.0731, 78.8686, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Vijayawada', 'Andhra Pradesh', 'Krishna', 'Vijayawada, Andhra Pradesh - 520001', NULL, 250, 'Gaushala in the commercial capital of Andhra Pradesh, serving rescued cattle of the Krishna delta.', 16.5062, 80.6480, 'web_search');
