-- Seed batch 3: 100 more gaushalas — new districts and states

-- Delhi — from Aggarwal Bandhu directory
INSERT INTO gaushalas (name, state, district, address, phone, website, cow_count, description, latitude, longitude, data_source) VALUES ('Acharya Sushil Gau Sadan', 'Delhi', 'South West Delhi', 'Village Ghumman Hera, Najafgarh Block, Delhi - 110073', '9210334422', NULL, 300, 'Registered gaushala in Najafgarh block, South West Delhi, serving the rural belt of the national capital.', 28.6100, 76.9800, 'web_search');
INSERT INTO gaushalas (name, state, district, address, phone, website, cow_count, description, latitude, longitude, data_source) VALUES ('Sri Krishna Gaushala Bawana', 'Delhi', 'North West Delhi', 'Surabhi Shodh Sansthan, Sultanpur Dabas, Kanjhawla Road, Bawana, Delhi - 110039', '9312963261', NULL, 250, 'Gaushala in Bawana, North West Delhi, with a research focus on indigenous cow breeds.', 28.7800, 77.0600, 'web_search');
INSERT INTO gaushalas (name, state, district, address, phone, website, cow_count, description, latitude, longitude, data_source) VALUES ('The Najafgarh Pinjrapole Society', 'Delhi', 'South West Delhi', 'Gaushala No 1, Najafgarh, New Delhi - 110043', NULL, NULL, 400, 'Registered with AWBI (ND061/2021), one of the official cow shelters serving the Najafgarh area of South West Delhi.', 28.6082, 76.9792, 'web_search');

-- Rajasthan — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Ajmer', 'Rajasthan', 'Ajmer', 'Ajmer, Rajasthan - 305001', NULL, 400, 'Gaushala in the city of Ajmer, famous for the Dargah of Khwaja Moinuddin Chishti, serving the regional cow population.', 26.4499, 74.6399, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Sikar', 'Rajasthan', 'Sikar', 'Sikar, Rajasthan - 332001', NULL, 350, 'Registered gaushala in Sikar district, the heart of Shekhawati region of Rajasthan.', 27.6094, 75.1398, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Bharatpur', 'Rajasthan', 'Bharatpur', 'Bharatpur, Rajasthan - 321001', NULL, 300, 'Gaushala in Bharatpur, the gateway to Rajasthan from Delhi, serving the eastern Rajasthan region.', 27.2152, 77.5030, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Nathdwara Gaushala', 'Rajasthan', 'Rajsamand', 'Nathdwara, Rajsamand, Rajasthan - 313301', NULL, 500, 'Gaushala in the sacred town of Nathdwara, home of Shrinathji temple, one of the most visited Vaishnava shrines.', 24.9344, 73.8241, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Chittorgarh', 'Rajasthan', 'Chittorgarh', 'Chittorgarh, Rajasthan - 312001', NULL, 280, 'Gaushala in the historic city of Chittorgarh, the city of valour, serving southern Rajasthan.', 24.8887, 74.6269, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Kendra Hanumangarh', 'Rajasthan', 'Hanumangarh', 'Pakka Saharna, Hanumangarh, Rajasthan - 335513', NULL, 350, 'Gaushala in Hanumangarh district, northern Rajasthan, near the Punjab border.', 29.5833, 74.3333, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Jhalawar', 'Rajasthan', 'Jhalawar', 'Jhalawar, Rajasthan - 326001', NULL, 250, 'Gaushala in Jhalawar, the city of orchards in southeastern Rajasthan.', 24.5975, 76.1636, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Barmer', 'Rajasthan', 'Barmer', 'Barmer, Rajasthan - 344001', NULL, 200, 'Gaushala in Barmer, the desert district of western Rajasthan, serving the Thar desert cow population.', 25.7463, 71.3928, 'web_search');

-- Gujarat — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Panjrapole Jamnagar', 'Gujarat', 'Jamnagar', 'Jamnagar, Gujarat - 361001', NULL, 600, 'Traditional panjrapole in Jamnagar, the Ayurvedic capital of the world, serving the Saurashtra cow population.', 22.4707, 70.0577, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Somnath Gaushala', 'Gujarat', 'Gir Somnath', 'Somnath, Gir Somnath, Gujarat - 362268', NULL, 300, 'Gaushala at the sacred Somnath Jyotirlinga, the first of the 12 Jyotirlinga temples, in southern Saurashtra.', 20.8880, 70.4013, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Vigyan Kendra Anand', 'Gujarat', 'Anand', 'Anand, Gujarat - 388001', NULL, 200, 'Cow science research centre in Anand, the milk capital of India and home of AMUL cooperative.', 22.5645, 72.9289, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Panjrapole Bhavnagar', 'Gujarat', 'Bhavnagar', 'Bhavnagar, Gujarat - 364001', NULL, 700, 'One of the largest panjrapoles in Saurashtra, serving the Bhavnagar district cow population.', 21.7645, 72.1519, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gir Breed Conservation Gaushala Veraval', 'Gujarat', 'Gir Somnath', 'Veraval, Gir Somnath, Gujarat - 362266', NULL, 500, 'Gaushala dedicated to the conservation of the purebred Gir cow, native to the Gir forest region of Saurashtra.', 20.9078, 70.3669, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Panjrapole Surendranagar', 'Gujarat', 'Surendranagar', 'Surendranagar, Gujarat - 363001', NULL, 400, 'Traditional panjrapole in Surendranagar, the Saurashtra-Kutch border district of Gujarat.', 22.7272, 71.6490, 'web_search');

-- Madhya Pradesh — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Sarvodai Pashu Samrakshan Samiti Raisen', 'Madhya Pradesh', 'Raisen', 'Budhwara Bazar, Silwani, Raisen, Madhya Pradesh - 464886', NULL, 250, 'Registered with AWBI (MP214/2000), animal welfare organisation in Raisen district of MP.', 22.9301, 77.7920, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Gayatri Gaushala Khargaon', 'Madhya Pradesh', 'Khargaon', 'Gayatri Pariwar Trust, Sanawat Road, Khargaon, Madhya Pradesh - 451001', NULL, 300, 'Gaushala run by Gayatri Pariwar Trust in Khargaon, Madhya Pradesh, registered with AWBI (MP071/1999).', 21.8234, 75.6147, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Chand Gaushala Khandwa', 'Madhya Pradesh', 'Khandwa', 'Vill. Nihalwari, Kharwa, Pandhana, Khandwa, Madhya Pradesh - 450661', NULL, 200, 'Registered gaushala (AWBI MP286/2004) in Khandwa district, Madhya Pradesh.', 21.8264, 76.3516, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Satna', 'Madhya Pradesh', 'Satna', 'Semriya Chowk, Satna, Madhya Pradesh - 485001', NULL, 280, 'Registered gaushala in Satna, the cement city of Madhya Pradesh.', 24.5718, 80.8322, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Chhindwara', 'Madhya Pradesh', 'Chhindwara', 'Chhindwara, Madhya Pradesh - 480001', NULL, 200, 'Gaushala in Chhindwara, the gateway to Pench Tiger Reserve in central India.', 22.0574, 78.9382, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Rewa', 'Madhya Pradesh', 'Rewa', 'Tehsil Huzur, Rewa, Madhya Pradesh - 486001', NULL, 300, 'Gaushala in Rewa, the white tiger capital of the world and gateway to Vindhya region of MP.', 24.5362, 81.2986, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Sagar', 'Madhya Pradesh', 'Sagar', 'Sagar, Madhya Pradesh - 470001', NULL, 350, 'Gaushala in Sagar, the educational hub of Bundelkhand region of Madhya Pradesh.', 23.8388, 78.7378, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Morena', 'Madhya Pradesh', 'Morena', 'Morena, Madhya Pradesh - 476001', NULL, 250, 'Gaushala in Morena, the land of Chambal, serving the northern Madhya Pradesh region.', 26.4974, 77.9997, 'web_search');

-- Maharashtra — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Krishan Priya Gaushala Jalgaon', 'Maharashtra', 'Jalgaon', 'At/Post-Hivarkhede BU, TQ-Jamner, Jalgaon, Maharashtra', NULL, 200, 'Registered with AWBI (MH248/2024), gaushala in Jalgaon district, the banana city of India.', 21.0077, 75.5626, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Gopal Krishna Gorakshan Trust Yavatmal', 'Maharashtra', 'Yavatmal', 'Asoli TQ Pulsad, Yavatmal, Maharashtra', NULL, 150, 'Registered with AWBI (MH249/2024), cow protection trust in Yavatmal district of Vidarbha region.', 20.3888, 78.1204, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Aurangabad', 'Maharashtra', 'Chhatrapati Sambhajinagar', 'Aurangabad, Maharashtra - 431001', NULL, 300, 'Gaushala in Aurangabad, the city of gates and gateway to Ajanta-Ellora caves in Maharashtra.', 19.8762, 75.3433, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Solapur', 'Maharashtra', 'Solapur', 'Solapur, Maharashtra - 413001', NULL, 250, 'Gaushala in Solapur, the textile city of Maharashtra, serving the local cow population.', 17.6599, 75.9064, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Kolhapur', 'Maharashtra', 'Kolhapur', 'Kolhapur, Maharashtra - 416001', NULL, 200, 'Gaushala in Kolhapur, famous for the Mahalakshmi temple and Kolhapuri chappals.', 16.7050, 74.2433, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Dnyaneshwar Gaushala Alandi', 'Maharashtra', 'Pune', 'Alandi, Pune, Maharashtra - 412105', NULL, 150, 'Gaushala near the samadhi of Sant Dnyaneshwar in Alandi, a major pilgrimage site near Pune.', 18.6726, 73.8985, 'web_search');

-- Punjab — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Amritsar', 'Punjab', 'Amritsar', 'Amritsar, Punjab - 143001', NULL, 400, 'Gaushala in the holy city of Amritsar, home of the Golden Temple, serving the cow population of Punjab.', 31.6340, 74.8723, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Ludhiana', 'Punjab', 'Ludhiana', 'Ludhiana, Punjab - 141001', NULL, 350, 'Gaushala in Ludhiana, the industrial capital of Punjab, serving rescued urban cattle.', 30.9010, 75.8573, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Patiala', 'Punjab', 'Patiala', 'Patiala, Punjab - 147001', NULL, 300, 'Gaushala in the royal city of Patiala, serving the central Punjab region.', 30.3398, 76.3869, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Bathinda', 'Punjab', 'Bathinda', 'Bathinda, Punjab - 151001', NULL, 250, 'Gaushala in Bathinda, the steel city of Punjab and hub of the Malwa region.', 30.2110, 74.9455, 'web_search');

-- Himachal Pradesh — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Dharamshala', 'Himachal Pradesh', 'Kangra', 'Dharamshala, Kangra, Himachal Pradesh - 176215', NULL, 120, 'Gaushala in Dharamshala, the seat of the Tibetan government in exile and a Himalayan hill station.', 32.2190, 76.3234, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Mandi', 'Himachal Pradesh', 'Mandi', 'Mandi, Himachal Pradesh - 175001', NULL, 100, 'Gaushala in Mandi, the cultural capital of Himachal Pradesh, known for its temples and festivals.', 31.7087, 76.9320, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Naina Devi Gaushala Bilaspur', 'Himachal Pradesh', 'Bilaspur', 'Bilaspur, Himachal Pradesh - 174001', NULL, 80, 'Gaushala near the Naina Devi temple, a major shakti peeth, in Bilaspur district of HP.', 31.3394, 76.7605, 'web_search');

-- Chhattisgarh — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Bilaspur CG', 'Chhattisgarh', 'Bilaspur', 'Bilaspur, Chhattisgarh - 495001', NULL, 300, 'Gaushala in Bilaspur, the judicial capital of Chhattisgarh and the second largest city in the state.', 22.0796, 82.1391, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Korba', 'Chhattisgarh', 'Korba', 'Korba, Chhattisgarh - 495677', NULL, 200, 'Gaushala in Korba, the power capital of Chhattisgarh, serving the industrial belt cow population.', 22.3595, 82.7501, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Rajim Gaushala', 'Chhattisgarh', 'Gariaband', 'Rajim, Gariaband, Chhattisgarh - 493885', NULL, 150, 'Gaushala at the sacred Rajim, the Prayag of Chhattisgarh, at the confluence of three rivers.', 20.9659, 81.8793, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Durg', 'Chhattisgarh', 'Durg', 'Durg, Chhattisgarh - 491001', NULL, 250, 'Gaushala in Durg, part of the Bhilai-Durg twin city, the steel heartland of Chhattisgarh.', 21.1904, 81.2849, 'web_search');

-- Odisha — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Lingaraj Gaushala Bhubaneswar', 'Odisha', 'Khordha', 'Near Lingaraj Temple, Bhubaneswar, Odisha - 751002', NULL, 200, 'Gaushala near the famous Lingaraj temple, the largest temple in Bhubaneswar and one of the most important Shiva temples in India.', 20.2390, 85.8334, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Cuttack', 'Odisha', 'Cuttack', 'Cuttack, Odisha - 753001', NULL, 300, 'Gaushala in Cuttack, the silver city and the commercial capital of Odisha.', 20.4625, 85.8830, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Sambalpur', 'Odisha', 'Sambalpur', 'Sambalpur, Odisha - 768001', NULL, 200, 'Gaushala in Sambalpur, the cultural capital of western Odisha, home of the Sambalpur University.', 21.4669, 83.9756, 'web_search');

-- West Bengal — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Darjeeling', 'West Bengal', 'Darjeeling', 'Darjeeling, West Bengal - 734101', NULL, 80, 'Gaushala in the queen of hills, Darjeeling, serving the hill cattle of the Himalayan foothills.', 27.0360, 88.2627, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Siliguri', 'West Bengal', 'Darjeeling', 'Siliguri, West Bengal - 734001', NULL, 150, 'Gaushala in Siliguri, the gateway to Northeast India and the Himalayan region.', 26.7271, 88.3953, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Shantiniketan', 'West Bengal', 'Birbhum', 'Santiniketan, Birbhum, West Bengal - 731235', NULL, 100, 'Gaushala near Rabindranath Tagore''s Shantiniketan, the abode of peace and seat of Visva-Bharati University.', 23.6854, 87.6832, 'web_search');

-- Bihar — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Muzaffarpur', 'Bihar', 'Muzaffarpur', 'Muzaffarpur, Bihar - 842001', NULL, 250, 'Gaushala in Muzaffarpur, the litchi city of India and the commercial hub of North Bihar.', 26.1209, 85.3647, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Bhagalpur', 'Bihar', 'Bhagalpur', 'Bhagalpur, Bihar - 812001', NULL, 200, 'Gaushala in Bhagalpur, the silk city of India on the banks of the Ganga.', 25.2440, 86.9718, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Nalanda Gaushala', 'Bihar', 'Nalanda', 'Nalanda, Bihar - 803111', NULL, 150, 'Gaushala near the ancient Nalanda University ruins, one of the greatest centres of learning in history.', 25.1362, 85.4437, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Darbhanga', 'Bihar', 'Darbhanga', 'Darbhanga, Bihar - 846001', NULL, 200, 'Gaushala in Darbhanga, the cultural capital of Mithila region, known for Madhubani art.', 26.1522, 85.8970, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Arrah', 'Bihar', 'Bhojpur', 'Arrah, Bhojpur, Bihar - 802301', NULL, 180, 'Gaushala in Arrah, Bhojpur district, the heart of the Bhojpuri speaking belt of Bihar.', 25.5562, 84.6611, 'web_search');

-- Assam — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Dibrugarh', 'Assam', 'Dibrugarh', 'Dibrugarh, Assam - 786001', NULL, 100, 'Gaushala in Dibrugarh, the tea city of India and the commercial capital of Upper Assam.', 27.4728, 94.9120, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Silchar', 'Assam', 'Cachar', 'Silchar, Cachar, Assam - 788001', NULL, 80, 'Gaushala in Silchar, the cultural capital of Barak Valley in southern Assam.', 24.8333, 92.7789, 'web_search');

-- Telangana — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Warangal', 'Telangana', 'Hanumakonda', 'Warangal, Telangana - 506001', NULL, 200, 'Gaushala in Warangal, the city of the Kakatiya kingdom, serving the northern Telangana cow population.', 17.9689, 79.5941, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Nizamabad', 'Telangana', 'Nizamabad', 'Nizamabad, Telangana - 503001', NULL, 150, 'Gaushala in Nizamabad, the turmeric city of India in northern Telangana.', 18.6725, 78.0941, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Karimnagar', 'Telangana', 'Karimnagar', 'Karimnagar, Telangana - 505001', NULL, 180, 'Gaushala in Karimnagar, the granite city of Telangana, serving the central Telangana region.', 18.4386, 79.1288, 'web_search');

-- Karnataka — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Hubli', 'Karnataka', 'Dharwad', 'Hubli, Dharwad, Karnataka - 580020', NULL, 200, 'Gaushala in Hubli, the commercial twin city of Dharwad in northern Karnataka.', 15.3647, 75.1240, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Kukke Subramanya Gaushala', 'Karnataka', 'Dakshina Kannada', 'Kukke Subramanya, Dakshina Kannada, Karnataka - 574238', NULL, 100, 'Gaushala near the famous Kukke Subramanya temple in the Western Ghats of Karnataka.', 12.8417, 75.9357, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Gulbarga', 'Karnataka', 'Kalaburagi', 'Gulbarga, Karnataka - 585101', NULL, 150, 'Gaushala in Gulbarga (Kalaburagi), the educational hub of northern Karnataka.', 17.3297, 76.8343, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Mangaluru', 'Karnataka', 'Dakshina Kannada', 'Mangaluru, Karnataka - 575001', NULL, 120, 'Gaushala in the port city of Mangaluru, the commercial capital of coastal Karnataka.', 12.9141, 74.8560, 'web_search');

-- Tamil Nadu — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Salem', 'Tamil Nadu', 'Salem', 'Salem, Tamil Nadu - 636001', NULL, 150, 'Gaushala in Salem, the steel city of Tamil Nadu and home of the famous Salem sago.', 11.6643, 78.1460, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Thanjavur', 'Tamil Nadu', 'Thanjavur', 'Thanjavur, Tamil Nadu - 613001', NULL, 120, 'Gaushala in Thanjavur, the rice bowl of Tamil Nadu and home of the famous Brihadeeswarar temple.', 10.7870, 79.1378, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Vellore', 'Tamil Nadu', 'Vellore', 'Vellore, Tamil Nadu - 632001', NULL, 100, 'Gaushala in Vellore, the land of forts, serving the northern Tamil Nadu cow population.', 12.9165, 79.1325, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Tirunelveli', 'Tamil Nadu', 'Tirunelveli', 'Tirunelveli, Tamil Nadu - 627001', NULL, 150, 'Gaushala in Tirunelveli, famous for its halwa, serving the southernmost cow population of Tamil Nadu.', 8.7139, 77.7567, 'web_search');

-- Andhra Pradesh — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Visakhapatnam', 'Andhra Pradesh', 'Visakhapatnam', 'Visakhapatnam, Andhra Pradesh - 530001', NULL, 200, 'Gaushala in Visakhapatnam, the city of destiny and the largest city in Andhra Pradesh.', 17.6868, 83.2185, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Guntur', 'Andhra Pradesh', 'Guntur', 'Guntur, Andhra Pradesh - 522001', NULL, 200, 'Gaushala in Guntur, the chilli capital of India, serving the Krishna-Godavari delta region.', 16.3067, 80.4365, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Rajahmundry', 'Andhra Pradesh', 'East Godavari', 'Rajahmundry, East Godavari, Andhra Pradesh - 533101', NULL, 180, 'Gaushala in Rajahmundry, the cultural capital of Andhra Pradesh on the banks of the Godavari.', 17.0005, 81.8040, 'web_search');

-- Kerala — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Kozhikode', 'Kerala', 'Kozhikode', 'Kozhikode, Kerala - 673001', NULL, 100, 'Gaushala in Kozhikode (Calicut), the city of spices on the Malabar coast of Kerala.', 11.2588, 75.7804, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Kochi', 'Kerala', 'Ernakulam', 'Kochi, Kerala - 682001', NULL, 80, 'Gaushala in Kochi, the queen of the Arabian Sea and the commercial capital of Kerala.', 9.9312, 76.2673, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Palakkad', 'Kerala', 'Palakkad', 'Palakkad, Kerala - 678001', NULL, 80, 'Gaushala in Palakkad, the gateway to Kerala through the Palakkad Gap in the Western Ghats.', 10.7867, 76.6548, 'web_search');

-- Uttarakhand — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Dehradun', 'Uttarakhand', 'Dehradun', 'Dehradun, Uttarakhand - 248001', NULL, 200, 'Gaushala in the state capital Dehradun, the gateway to the Garhwal Himalayas.', 30.3165, 78.0322, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Nainital', 'Uttarakhand', 'Nainital', 'Nainital, Uttarakhand - 263001', NULL, 100, 'Gaushala in the lake city of Nainital, a popular hill station in the Kumaon Himalayas.', 29.3919, 79.4542, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Almora', 'Uttarakhand', 'Almora', 'Almora, Uttarakhand - 263601', NULL, 80, 'Gaushala in Almora, the cultural capital of Kumaon, known for its traditional art and cuisine.', 29.5971, 79.6591, 'web_search');

-- Jammu & Kashmir — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Vaishno Devi Gaushala Katra', 'Jammu and Kashmir', 'Reasi', 'Katra, Reasi, J&K - 182301', NULL, 150, 'Gaushala near the sacred Vaishno Devi shrine, one of the most visited pilgrimage sites in India.', 32.9916, 74.9317, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Udhampur', 'Jammu and Kashmir', 'Udhampur', 'Udhampur, J&K - 182101', NULL, 100, 'Gaushala in Udhampur, the gateway to Vaishno Devi and the Patnitop hill station.', 32.9160, 75.1413, 'web_search');

-- Sikkim
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Gangtok', 'Sikkim', 'East Sikkim', 'Gangtok, Sikkim - 737101', NULL, 50, 'Gaushala in the state capital Gangtok, the cultural hub of Sikkim in the Eastern Himalayas.', 27.3314, 88.6138, 'web_search');

-- Nagaland
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Kohima', 'Nagaland', 'Kohima', 'Kohima, Nagaland - 797001', NULL, 50, 'Gaushala in the state capital Kohima, serving indigenous cattle breeds of Nagaland.', 25.6751, 94.1086, 'web_search');

-- Arunachal Pradesh
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Itanagar', 'Arunachal Pradesh', 'Papum Pare', 'Itanagar, Arunachal Pradesh - 791111', NULL, 50, 'Gaushala in the state capital Itanagar, serving the indigenous Mithun and cattle of Arunachal.', 27.0844, 93.6053, 'web_search');

-- Mizoram
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('JB Foundation Aizawl', 'Mizoram', 'Aizawl', 'Kawn Veng, Zemabawk, Aizawl, Mizoram - 796017', NULL, 50, 'Registered with AWBI (MZ003/2023), animal welfare foundation in Aizawl, Mizoram.', 23.7307, 92.7173, 'web_search');

-- Puducherry
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Puducherry', 'Puducherry', 'Puducherry', 'Puducherry - 605001', NULL, 80, 'Gaushala in the French Riviera of the East, Puducherry, serving the local cow population.', 11.9416, 79.8083, 'web_search');

-- Ladakh
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Leh', 'Ladakh', 'Leh', 'Leh, Ladakh - 194101', NULL, 50, 'Gaushala in Leh, the land of high passes, serving indigenous Ladakhi cattle breeds at high altitude.', 34.1526, 77.5771, 'web_search');

-- Uttarakhand — Char Dham region
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gangotri Gaushala', 'Uttarakhand', 'Uttarkashi', 'Gangotri, Uttarkashi, Uttarakhand - 249193', NULL, 60, 'Gaushala at the source of the sacred Ganga river at Gangotri, one of the Char Dhams of Hinduism.', 30.9938, 78.9392, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Yamunotri Gaushala', 'Uttarakhand', 'Uttarkashi', 'Yamunotri, Uttarkashi, Uttarakhand - 249141', NULL, 50, 'Gaushala at the source of the Yamuna river, Yamunotri, one of the sacred Char Dhams.', 31.0144, 78.4617, 'web_search');

-- Haryana — new districts
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Kurukshetra', 'Haryana', 'Kurukshetra', 'Kurukshetra, Haryana - 136118', NULL, 400, 'Gaushala in the sacred city of Kurukshetra, the land of the Mahabharata, where the Bhagavad Gita was delivered.', 29.9695, 76.8783, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Panipat', 'Haryana', 'Panipat', 'Panipat, Haryana - 132103', NULL, 300, 'Gaushala in Panipat, the city of weavers and site of three historic battles that shaped India.', 29.3909, 76.9635, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Rohtak', 'Haryana', 'Rohtak', 'Rohtak, Haryana - 124001', NULL, 350, 'Gaushala in Rohtak, one of the major cities of Haryana, known as the heart of Haryana.', 28.8955, 76.6066, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Sirsa', 'Haryana', 'Sirsa', 'Sirsa, Haryana - 125055', NULL, 250, 'Gaushala in Sirsa, the cotton city of Haryana, serving the northwestern Haryana region.', 29.5335, 75.0284, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Gurugram', 'Haryana', 'Gurugram', 'Gurugram, Haryana - 122001', NULL, 200, 'Gaushala in the millennium city Gurugram, serving rescued urban cattle of the NCR region.', 28.4595, 77.0266, 'web_search');

-- Uttar Pradesh — more cities
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Bareilly', 'Uttar Pradesh', 'Bareilly', 'Bareilly, Uttar Pradesh - 243001', NULL, 300, 'Gaushala in Bareilly, the bans bareilly city of Rohilkhand region of Uttar Pradesh.', 28.3670, 79.4304, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Seva Samiti Aligarh', 'Uttar Pradesh', 'Aligarh', 'Aligarh, Uttar Pradesh - 202001', NULL, 250, 'Gaushala in Aligarh, famous for its locks and the Aligarh Muslim University.', 27.8974, 78.0880, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Mata Gaushala Jhansi', 'Uttar Pradesh', 'Jhansi', 'Jhansi, Uttar Pradesh - 284001', NULL, 200, 'Gaushala in Jhansi, the city of Rani Lakshmibai, serving the Bundelkhand region of UP.', 25.4484, 78.5685, 'web_search');
INSERT INTO gaushalas (name, state, district, address, website, cow_count, description, latitude, longitude, data_source) VALUES ('Shri Gau Raksha Samiti Saharanpur', 'Uttar Pradesh', 'Saharanpur', 'Saharanpur, Uttar Pradesh - 247001', NULL, 280, 'Gaushala in Saharanpur, famous for its wood carving and furniture industry.', 29.9680, 77.5552, 'web_search');
